{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentsmith-hub.frontend.fullname" . }}
  labels:
    {{- include "agentsmith-hub.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "agentsmith-hub.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "agentsmith-hub.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agentsmith-hub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.securityContext | nindent 8 }}
      containers:
        - name: frontend
          image: {{ include "agentsmith-hub.frontend.image" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.frontend.containerSecurityContext | nindent 12 }}
          env:
            - name: API_BASE_URL
              value: {{ .Values.config.frontend.apiBaseUrl | quote }}
            - name: API_TIMEOUT
              value: {{ .Values.config.frontend.apiTimeout | toString }}
            - name: DEBUG_MODE
              value: {{ .Values.config.frontend.enableDebugMode | toString }}
            - name: CLUSTER_MODE
              value: {{ .Values.config.frontend.enableClusterMode | toString }}
            - name: THEME
              value: {{ .Values.config.frontend.theme | quote }}
            - name: LANGUAGE
              value: {{ .Values.config.frontend.language | quote }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/config.json
              subPath: frontend-config.json
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "agentsmith-hub.configVolumeName" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentsmith-hub.frontend.fullname" . }}
  labels:
    {{- include "agentsmith-hub.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agentsmith-hub.frontend.selectorLabels" . | nindent 4 }}
{{- if .Values.frontend.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agentsmith-hub.frontend.fullname" . }}
  labels:
    {{- include "agentsmith-hub.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.frontend.ingress.className }}
  ingressClassName: {{ .Values.frontend.ingress.className }}
  {{- end }}
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- range .Values.frontend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "agentsmith-hub.frontend.fullname" $ }}
                port:
                  number: {{ $.Values.frontend.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }} 