{{- if .Values.leader.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentsmith-hub.leader.fullname" . }}
  labels:
    {{- include "agentsmith-hub.leader.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.leader.replicaCount }}
  selector:
    matchLabels:
      {{- include "agentsmith-hub.leader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "agentsmith-hub.leader.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agentsmith-hub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.leader.securityContext | nindent 8 }}
      containers:
        - name: agentsmith-hub
          image: {{ include "agentsmith-hub.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--config_root"
            - "{{ .Values.leader.config.configRoot }}"
            - "--leader"
            - "--port"
            - "{{ .Values.leader.config.port | toString }}"
          ports:
            - name: http
              containerPort: {{ .Values.leader.config.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.leader.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.leader.containerSecurityContext | nindent 12 }}
          env:
            - name: REDIS_HOST
              value: {{ include "agentsmith-hub.redis.fullname" . }}
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password | quote }}
            - name: NODE_ID
              value: "leader"
            - name: LOG_LEVEL
              value: {{ .Values.config.agentsmith.logLevel | quote }}
            - name: CONFIG_ROOT
              value: {{ .Values.leader.config.configRoot | quote }}
            - name: MCP_ENABLED
              value: "true"
            - name: AGENTSMITH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "agentsmith-hub.fullname" . }}-token
                  key: token
          volumeMounts:
            - name: config
              mountPath: {{ .Values.leader.config.configRoot }}
            - name: logs
              mountPath: /tmp/hub_logs
            - name: lib
              mountPath: /opt/lib
            - name: mcp-config
              mountPath: /opt/mcp_config
      {{- with .Values.leader.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.leader.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.leader.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "agentsmith-hub.configVolumeName" . }}
        - name: logs
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "agentsmith-hub.logsVolumeName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: lib
          emptyDir: {}
        - name: mcp-config
          configMap:
            name: {{ include "agentsmith-hub.mcpConfigVolumeName" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentsmith-hub.leader.fullname" . }}
  labels:
    {{- include "agentsmith-hub.leader.labels" . | nindent 4 }}
  {{- with .Values.leader.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.leader.service.type }}
  ports:
    - port: {{ .Values.leader.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agentsmith-hub.leader.selectorLabels" . | nindent 4 }}
{{- if .Values.leader.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agentsmith-hub.leader.fullname" . }}
  labels:
    {{- include "agentsmith-hub.leader.labels" . | nindent 4 }}
  {{- with .Values.leader.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.leader.ingress.className }}
  ingressClassName: {{ .Values.leader.ingress.className }}
  {{- end }}
  {{- if .Values.leader.ingress.tls }}
  tls:
    {{- range .Values.leader.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.leader.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "agentsmith-hub.leader.fullname" $ }}
                port:
                  number: {{ $.Values.leader.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agentsmith-hub.logsVolumeName" . }}
  labels:
    {{- include "agentsmith-hub.leader.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
{{- end }} 