{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentsmith-hub.redis.fullname" . }}
  labels:
    {{- include "agentsmith-hub.redis.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "agentsmith-hub.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "agentsmith-hub.redis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.redis.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agentsmith-hub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.redis.securityContext | nindent 8 }}
      containers:
        - name: redis
          image: {{ include "agentsmith-hub.redis.image" . }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.redis.master.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.redis.containerSecurityContext | nindent 12 }}
          env:
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password | quote }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: redis-data
          {{- if .Values.redis.master.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "agentsmith-hub.redis.dataVolumeName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: redis-config
          configMap:
            name: {{ include "agentsmith-hub.redis.configVolumeName" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentsmith-hub.redis.fullname" . }}
  labels:
    {{- include "agentsmith-hub.redis.labels" . | nindent 4 }}
  {{- with .Values.redis.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "agentsmith-hub.redis.selectorLabels" . | nindent 4 }}
{{- if .Values.redis.master.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agentsmith-hub.redis.dataVolumeName" . }}
  labels:
    {{- include "agentsmith-hub.redis.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.redis.master.persistence.storageClass }}
  storageClassName: {{ .Values.redis.master.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.master.persistence.size }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentsmith-hub.redis.configVolumeName" . }}
  labels:
    {{- include "agentsmith-hub.redis.labels" . | nindent 4 }}
data:
  redis.conf: |
    # Redis configuration for AgentSmith-HUB
    bind 0.0.0.0
    port 6379
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    databases 16
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
    requirepass {{ .Values.redis.auth.password }}
{{- end }} 