name: Build and Release AgentSmith-HUB

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  BINARY_NAME: agentsmith-hub

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for git info
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd web
        npm ci
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: Build project
      run: |
        make all
    
    - name: Get version info
      id: version
      run: |
        VERSION=$(cat VERSION 2>/dev/null || echo "unknown")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Set release name based on tag or branch
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          RELEASE_NAME=${GITHUB_REF#refs/tags/}
        else
          RELEASE_NAME="$VERSION-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
        fi
        echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT
    
    - name: Create deployment archive
      run: |
        cd dist
        tar --create --gzip --file=../agentsmith-hub-${{ steps.version.outputs.release_name }}-linux-amd64.tar.gz .
        cd ..
        
        # Create checksum
        sha256sum agentsmith-hub-${{ steps.version.outputs.release_name }}-linux-amd64.tar.gz > agentsmith-hub-${{ steps.version.outputs.release_name }}-linux-amd64.tar.gz.sha256
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: agentsmith-hub-${{ steps.version.outputs.release_name }}-linux-amd64
        path: |
          agentsmith-hub-${{ steps.version.outputs.release_name }}-linux-amd64.tar.gz
          agentsmith-hub-${{ steps.version.outputs.release_name }}-linux-amd64.tar.gz.sha256
        retention-days: 30
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          agentsmith-hub-${{ steps.version.outputs.release_name }}-linux-amd64.tar.gz
          agentsmith-hub-${{ steps.version.outputs.release_name }}-linux-amd64.tar.gz.sha256
        body: |
          ## AgentSmith-HUB Release ${{ github.ref_name }}
          
          ### What's Included
          
          - Pre-built Linux binary (amd64)
          - Frontend web application
          - Required libraries (librure.so)
          - Configuration templates
          - Start and stop scripts
          - Deployment documentation
          
          ### Quick Start
          
          1. Download and extract the archive
          2. Configure your settings in `config/config.yaml`
          3. Run `./start.sh` to start the application
          4. Access the web interface at http://localhost:8080
          
          ### Version Information
          
          - Version: ${{ steps.version.outputs.version }}
          - Git Commit: ${{ github.sha }}
          - Build Date: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          
          See README.md in the package for detailed deployment instructions.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 