name: Build and Release AgentSmith-HUB

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  BINARY_NAME: agentsmith-hub

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for git info
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd web
        npm ci
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        # Install cross-compilation tools for ARM64
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          sudo apt-get install -y gcc-aarch64-linux-gnu
        fi
    
    - name: Build frontend
      run: |
        cd web
        npm run build
    
    - name: Build backend
      run: |
        cd src
        mkdir -p ../build
        
        # Set architecture-specific build variables
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          export CC=aarch64-linux-gnu-gcc
          export CGO_ENABLED=1
          export GOOS=linux
          export GOARCH=arm64
          LIB_PATH="$(pwd)/../lib/linux/arm64"
          export CGO_LDFLAGS="-L${LIB_PATH} -lrure -Wl,-rpath,${LIB_PATH}"
          export LD_LIBRARY_PATH="${LIB_PATH}:$LD_LIBRARY_PATH"
        else
          export CGO_ENABLED=1
          export GOOS=linux
          export GOARCH=amd64
          LIB_PATH="$(pwd)/../lib/linux/amd64"
          export CGO_LDFLAGS="-L${LIB_PATH} -lrure -Wl,-rpath,${LIB_PATH}"
          export LD_LIBRARY_PATH="${LIB_PATH}:$LD_LIBRARY_PATH"
        fi
        
        # Debug: Show current directory and file structure
        echo "Current directory: $(pwd)"
        echo "Library directory structure:"
        find ../lib -type f -name "*.so" 2>/dev/null || echo "No .so files found"
        
        # Verify library exists and show debug info
        echo "Expected library path: ${LIB_PATH}"
        if [ -f "${LIB_PATH}/librure.so" ]; then
          echo "✓ Library file found"
          ls -la "${LIB_PATH}/"
        else
          echo "✗ Library file not found, checking alternative locations..."
          # Check if library exists in alternative locations
          if [ -f "../lib/linux/librure.so" ]; then
            echo "Found library in ../lib/linux/"
            LIB_PATH="../lib/linux"
          elif [ -f "../lib/librure.so" ]; then
            echo "Found library in ../lib/"
            LIB_PATH="../lib"
          else
            echo "ERROR: Cannot find librure.so in any expected location"
            echo "Directory contents:"
            ls -la ../lib/ || echo "lib directory not found"
            exit 1
          fi
        fi
        
        # Update CGO flags with correct path
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          export CGO_LDFLAGS="-L${LIB_PATH} -lrure -Wl,-rpath,${LIB_PATH}"
        else
          export CGO_LDFLAGS="-L${LIB_PATH} -lrure -Wl,-rpath,${LIB_PATH}"
        fi
        export LD_LIBRARY_PATH="${LIB_PATH}:$LD_LIBRARY_PATH"
        
        echo "Updated CGO_LDFLAGS: $CGO_LDFLAGS"
        echo "Updated LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
        
        # Build with version information
        VERSION=$(cat ../VERSION 2>/dev/null | tr -d '\n\r ' || echo "unknown")
        BUILD_TIME=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
        GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
        LDFLAGS="-s -w -X 'main.Version=$VERSION' -X 'main.BuildTime=$BUILD_TIME' -X 'main.GitCommit=$GIT_COMMIT'"
        
        # Copy library to system path for linking
        echo "Copying library to system path..."
        sudo cp "${LIB_PATH}/librure.so" /usr/lib/
        sudo ldconfig
        
        # Build the binary
        echo "Building binary..."
        if go build -ldflags "$LDFLAGS" -o ../build/${BINARY_NAME}-${{ matrix.arch }} .; then
          echo "✓ Build completed successfully"
          ls -la ../build/${BINARY_NAME}-${{ matrix.arch }}
          echo "Checking binary dependencies:"
          ldd ../build/${BINARY_NAME}-${{ matrix.arch }} || echo "ldd not available"
        else
          echo "✗ Build failed"
          exit 1
        fi
    
    - name: Get version info
      id: version
      run: |
        VERSION=$(cat VERSION 2>/dev/null | tr -d '\n\r ' || echo "unknown")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Set release name based on tag or branch
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          RELEASE_NAME=${GITHUB_REF#refs/tags/}
        else
          RELEASE_NAME="${VERSION}-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
        fi
        # Remove any spaces and newlines from release name
        RELEASE_NAME=$(echo "$RELEASE_NAME" | tr -d '\n\r ')
        echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT
    
    - name: Create deployment archive
      run: |
        # Create a clean directory structure for the archive
        RELEASE_NAME="${{ steps.version.outputs.release_name }}"
        ARCHIVE_DIR="agentsmith-hub"
        ARCHIVE_NAME="agentsmith-hub-${{ matrix.arch }}.tar.gz"
        
        echo "Creating archive: $ARCHIVE_NAME"
        echo "Architecture: ${{ matrix.arch }}"
        
        # Create the archive directory
        mkdir -p "$ARCHIVE_DIR"
        
        # Copy binary (rename to standard name)
        cp "build/${BINARY_NAME}-${{ matrix.arch }}" "$ARCHIVE_DIR/$BINARY_NAME"
        chmod +x "$ARCHIVE_DIR/$BINARY_NAME"
        
        # Copy frontend files
        cp -r web/dist "$ARCHIVE_DIR/web"
        
        # Copy architecture-specific libraries
        mkdir -p "$ARCHIVE_DIR/lib"
        cp -r "lib/linux/${{ matrix.arch }}"/* "$ARCHIVE_DIR/lib/"
        
        # Copy configuration files
        cp -r config "$ARCHIVE_DIR/"
        cp -r mcp_config "$ARCHIVE_DIR/"
        
        # Copy nginx configuration
        mkdir -p "$ARCHIVE_DIR/nginx"
        cp script/nginx.conf "$ARCHIVE_DIR/nginx/nginx.conf"
        
        # Generate architecture-aware scripts
        chmod +x ./script/create_scripts.sh
        ./script/create_scripts.sh "$ARCHIVE_DIR" "${{ matrix.arch }}"
        
        # Copy documentation
        cp README.md "$ARCHIVE_DIR/"
        cp VERSION "$ARCHIVE_DIR/"
        
        # Show what we're packaging
        echo "Contents to be archived:"
        find "$ARCHIVE_DIR" -type f | head -20
        echo "..."
        
        # Create the tar.gz archive
        tar -czf "$ARCHIVE_NAME" "$ARCHIVE_DIR"
        
        # Create checksum
        sha256sum "$ARCHIVE_NAME" > "${ARCHIVE_NAME}.sha256"
        
        # Clean up
        rm -rf "$ARCHIVE_DIR"
        
        echo "Archive created successfully: $ARCHIVE_NAME"
        ls -la *.tar.gz*
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: agentsmith-hub-${{ matrix.arch }}-${{ steps.version.outputs.release_name }}
        path: |
          agentsmith-hub-${{ matrix.arch }}.tar.gz
          agentsmith-hub-${{ matrix.arch }}.tar.gz.sha256
        retention-days: 30
    
    - name: Upload binary for Docker
      uses: actions/upload-artifact@v4
      with:
        name: agentsmith-hub-${{ matrix.arch }}-binary
        path: |
          build/${BINARY_NAME}-${{ matrix.arch }}
          web/dist/
        retention-days: 30
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          agentsmith-hub-${{ matrix.arch }}.tar.gz
          agentsmith-hub-${{ matrix.arch }}.tar.gz.sha256
        body: |
          ## AgentSmith-HUB Release ${{ github.ref_name }}
          
          ### What's Included
          
          - Pre-built Linux binary (${{ matrix.arch }})
          - Frontend web application
          - Required libraries (librure.so for ${{ matrix.arch }})
          - Configuration templates
          - Nginx configuration for web serving
          - Architecture-aware start and stop scripts
          - Deployment documentation
          
          ### Quick Start
          
          1. Download the appropriate archive for your architecture:
             - For AMD64: `agentsmith-hub-amd64.tar.gz`
             - For ARM64: `agentsmith-hub-arm64.tar.gz`
          
          2. Extract and deploy:
             ```bash
             tar -xzf agentsmith-hub-${{ matrix.arch }}.tar.gz
             cd agentsmith-hub
             ```
          
          3. Configure your settings in `config/config.yaml`
          
          4. (Optional) Configure nginx for web serving:
             ```bash
             sudo cp nginx/agentsmith-hub.conf /etc/nginx/conf.d/
             # Edit the path in the config file if needed
             sudo nginx -t && sudo systemctl reload nginx
             ```
          
          5. Run `./start.sh` to start the application
          
          6. Access the web interface:
             - With nginx: http://localhost
             - Direct backend: http://localhost:8080
          
          ### Architecture Support
          
          - **AMD64**: Standard x86_64 architecture (Intel/AMD processors)
          - **ARM64**: ARM 64-bit architecture (Apple Silicon, ARM servers)
          
          The scripts automatically detect your system architecture and use the appropriate libraries.
          
          ### Version Information
          
          - Version: ${{ steps.version.outputs.version }}
          - Architecture: ${{ matrix.arch }}
          - Git Commit: ${{ github.sha }}
          - Build Date: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          
          See README.md in the package for detailed deployment instructions.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    env:
      BINARY_NAME: agentsmith-hub
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Prepare Docker build context
      run: |
        # Debug: Show current working directory and contents
        echo "Current working directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        
        # Create build directory structure for Docker
        mkdir -p build-docker
        
        # Extract binaries from artifacts
        echo "Extracting artifacts..."
        for arch in amd64 arm64; do
          if [ -d "artifacts/agentsmith-hub-${arch}-binary" ]; then
            echo "Found artifact for ${arch}"
            # Find the binary in the artifact
            BINARY_PATH=$(find "artifacts/agentsmith-hub-${arch}-binary" -name "${BINARY_NAME}-${arch}" -type f | head -1)
            if [ -n "$BINARY_PATH" ]; then
              cp "$BINARY_PATH" "build-docker/agentsmith-hub-${arch}"
              chmod +x "build-docker/agentsmith-hub-${arch}"
              echo "✓ Copied ${arch} binary from artifacts"
            else
              echo "✗ Could not find ${arch} binary in artifacts"
              find "artifacts/agentsmith-hub-${arch}-binary" -type f
              exit 1
            fi
          else
            echo "✗ Artifact for ${arch} not found"
            ls -la artifacts/
            exit 1
          fi
        done
        
        # Copy web frontend from one of the artifacts (use amd64 artifact)
        WEB_DIST_PATH="artifacts/agentsmith-hub-amd64-binary/dist"
        if [ -d "$WEB_DIST_PATH" ]; then
          cp -r "$WEB_DIST_PATH" web-dist
          echo "✓ Copied web frontend from artifacts"
        else
          echo "✗ Web frontend not found in artifacts"
          find artifacts -type d
          exit 1
        fi
        
        echo "Prepared Docker build context:"
        ls -la build-docker/
        echo "Web dist contents:"
        ls -la web-dist/ | head -10
        
    - name: Get version info
      id: version
      run: |
        VERSION=$(cat VERSION 2>/dev/null | tr -d '\n\r ' || echo "unknown")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=${{ steps.version.outputs.version }}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VERSION=${{ steps.version.outputs.version }}
          GIT_COMMIT=${{ github.sha }}
          BUILD_TIME=${{ github.event.head_commit.timestamp || github.event.repository.updated_at }}